SECRET_KEY = 'vpU=Xm=zAQEUoUOpXhJF4oRhJmCaTBTQQDwvH40L1lXT'
SALT = 'UWZUaldtWnE0dDd3IXolQw=='
IV = 'blpyNHU3eCFBJUQqRy1LYQ=='

MYSQL_HOST = 'localhost'
MYSQL_USER = 'kjrppo'
MYSQL_PASSWORD = 'opprjk'
MYSQL_DATABASE = 'enigma'

ORACLE_USER = 'KJRPPO'
ORACLE_PASSWORD = 'opprjk'
ORACLE_HOST = '10.1.9.115'
ORACLE_PORT = '1521'
SERVICE_NAME = 'TEST'

SCANER_ID = '2'

ENTER = '2'
LEAVE = '3'
