SECRET_KEY = 'vpU=Xm=zAQEUoUOpXhJF4oRhJmCaTBTQQDwvH40L1lXT'
SALT = 'UWZUaldtWnE0dDd3IXolQw=='
IV = 'blpyNHU3eCFBJUQqRy1LYQ=='

ORACLE_USER = 'KJRPPO' 
ORACLE_PASSWORD = 'opprjk'
ORACLE_HOST = '10.1.9.115' 
ORACLE_PORT = '1521' 
SERVICE_NAME ='BPSC'